### ISSUE TITLE
support Angular 10

### ISSUE THREAD

**Issue by igorlino** [annapogorelova/ng-go-top-button#1]
Hello,

there is a npm warning on installation of the modules when using Angular 10.0.4.

It works fine, so its only a cosmetic warning, but would be good to update the package.json of the library allowing that version of angular

![image](https://user-images.githubusercontent.com/10480442/91944228-0b151200-ecfe-11ea-9d31-b9466b03fa99.png)

Thanks

**Comment by annapogorelova** [comment]
Hey @igorlino, sorry for the late reply. I published a new version 10.0.0 to npm, which targets Angular 10, please check.

**Comment by igorlino** [comment]
Thanks a lot :)

**Comment by igorlino** [comment]
Very strange, after updating, it does not find the module any longer. It seems the structure of the output library changed.

**Comment by annapogorelova** [comment]
@igorlino, sorry, I did the publishing wrong. The 10.0.1 version is fine :)

**Comment by igorlino** [comment]
awesome, it works :) thanks a lot
